* COMMENT License Notice
** Copyright 2017 Michael Cornelius
** GPL3
This file is part of org-shopping-list.

org-shopping-list is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

org-shopping-list is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with org-shopping-list.  If not, see
<http://www.gnu.org/licenses/>.

* org-shopping-list

org-shopping-list is a simple shopping list application implemented on
Org for Emacs.

** Installation

Get the code by cloning the repository: 
~git clone https://github.com/emdeesee/org-shopping-list.git~

Load the library in your emacs session. Add the following code, or
something similar to init.el

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path <path to parent directory of clone repository>)
(load-library "org-shopping-list")
#+END_SRC

** Usage

By default your shopping list will be stored in
"\~/Org/shopping-list.org". This value is stored in the variable
~org-shopping-list-file~; you can change this setting to suit your
needs.

Your shopping list uses the todo keywords HAVE and NEED. The
interactive command ~org-shopping-list-add~ is used to add items to
the list. It will search for the item, and simply toggle it to a NEED
state if it's already there.

To see your list, ~M-x org-shopping-list-show~ will open an agenda
view buffer with your list. When you're done, 's' will save your
shopping list.

** TODO [0/3] Some things to add
- [ ] Keybindings for add/show
- [ ] Customization for keywords and shopping list file
- [ ] Packaging

